export const baseURL = process.env.NEXT_PUBLIC_API_BASEURL;
export const siteURL = process.env.NEXT_PUBLIC_SITE_URL;

export const generals = {
  logo: "/assets/logo/logo.svg",
  site_name: "Batubutik",
  free_shipping: 1000,
  shipping_price: 50,
  socials: [
    { platform: "Facebook", url: "/" },
    { platform: "Twitter", url: "/" },
    { platform: "İnstagram", url: "/" },
    { platform: "Youtube", url: "/" },
  ],
  address: "Meclis Mahallesi Derviş Sk. Fuat Ozal Apt No 38/1 Sancaktepe",
  email: "batubutik@info.com",
  phone: "08505058515",
  whatsapp_number: "05555058515",
  tags: [
    "Dantel İç Giyim",
    "Ekonomik İç Giyim",
    "Fantezi giyim",
    "Kadın iç giyim",
    "Kadın İç Çamaşır",
    "Likra İç Giyim",
    "Lüks İç Giyim",
    "Takım İç Giyim",
  ],
  return_conditions: "İptal ve İade Koşulları Henüz Belirtilmemiş!",
};

export const navLinks = [
  {
    title: "Blog",
    url: "/blog",
  },
  {
    title: "Hakkımızda",
    url: "/hakkimizda",
  },
  {
    title: "İletişim",
    url: "/iletisim",
  },
];

export const categories = [
  {
    name: "Erkek",
    slug: "erkek",
    product_count: 0,
    sub_categories: [
      { name: "Üst Giyim", slug: "ust-giyim", product_count: 0 },
      { name: "Alt Giyim", slug: "alt-giyim", product_count: 0 },
    ],
  },
  {
    name: "Kadın",
    slug: "kadin",
    product_count: 6,
    sub_categories: [
      { name: "Üst Giyim", slug: "ust-giyim", product_count: 0 },
      { name: "Alt Giyim", slug: "alt-giyim", product_count: 0 },
      { name: "İç Giyim", slug: "ic-giyim", product_count: 6 },
    ],
  },
  {
    name: "Çocuk",
    slug: "cocuk",
    product_count: 0,
    sub_categories: [
      { name: "Üst Giyim", slug: "ust-giyim", product_count: 0 },
      { name: "Alt Giyim", slug: "alt-giyim", product_count: 0 },
    ],
  },
  {
    name: "Aksesuar",
    slug: "aksesuar",
    product_count: 0,
  },
];

export const instantProducts = [
  {
    id: 1,
    title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
    short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
    slug: "amor-bralet-jartiyer-ic-camasir-takimi",
    code: "ABJ-100",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product5.webp",
      "/assets/products/product2.webp",
      "/assets/products/product3.webp",
      "/assets/products/product4.webp",
      "/assets/products/product.webp",
    ],
    rating: 4.9,
    price: 460,
    discount: 10,
    stock: 50,
    choise_required: false,
    attributes: [
      {
        required: true,
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
          { option_name: "M", option_stock: 50 },
          { option_name: "L", option_stock: 50 },
          { option_name: "XL", option_stock: 50 },
          { option_name: "XXL", option_stock: 0 },
          { option_name: "3XL", option_stock: 50 },
          { option_name: "4XL", option_stock: 50 },
          { option_name: "5XL", option_stock: 50 },
        ],
      },
      {
        required: true,
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 2,
    title: "Black Bralet Dress",
    short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
    slug: "black-bralet-dress",
    code: "BBD-101",
    brand: "Batubutik",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product6.webp",
      "/assets/products/product7.webp",
      "/assets/products/product8.webp",
      "/assets/products/product9.webp",
    ],
    rating: 4.4,
    price: 320,
    discount: 30,
    stock: 50,
    choise_required: false,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
          { option_name: "M", option_stock: 50 },
        ],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 3,
    title: "Burgundy Bralet Dress",
    short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
    slug: "burgundy-bralet-dress",
    code: "BBD-102",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product11.webp",
      "/assets/products/product12.webp",
      "/assets/products/product16.webp",
      "/assets/products/product17.webp",
    ],
    rating: 4.1,
    price: 370,
    discount: 0,
    stock: 50,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
          { option_name: "M", option_stock: 50 },
        ],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 4,
    title: "Blue Bralet Dress",
    short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
    slug: "blue-bralet-dress",
    code: "BBD-103",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product14.webp",
      "/assets/products/product15.webp",
      "/assets/products/product16.webp",
    ],
    rating: 3.8,
    price: 410,
    discount: 15,
    stock: 50,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
        ],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 5,
    title: "Burgundy Bralet Dress 2",
    short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
    slug: "burgundy-bralet-dress-2",
    code: "BBD-104",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product17.webp",
      "/assets/products/product11.webp",
      "/assets/products/product12.webp",
      "/assets/products/product16.webp",
    ],
    rating: 2.4,
    price: 410,
    discount: 0,
    stock: 0,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [{ option_name: "5XL", option_stock: 50 }],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 6,
    title: "Tek Fotoğraflı Ürün",
    short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
    slug: "tek-fotograf-urun",
    code: "TFU-100",
    brand: null,
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: ["/assets/products/product15.webp"],
    rating: 2.4,
    price: 410,
    discount: 0,
    stock: 10,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [{ option_name: "5XL", option_stock: 50 }],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-15T13:24:59.000000Z"),
    updated_at: null,
  },
];

export const instantProductDetail = {
  title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
  short_content: "Ürünümüz standart bedenler için uygundur. Rahat kalıptır.",
  slug: "amor-bralet-jartiyer-ic-camasir-takimi",
  content:
    `<h1>Başlık H1</h1>` +
    `</br>` +
    `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae doloremque, praesentium autem placeat obcaecati voluptates, at adipisci laborum nulla temporibus assumenda laudantium sit labore? Architecto dicta repudiandae quisquam minus mollitia.</p>` +
    `<h2>Başlık H2</h2>` +
    `</br>` +
    `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae doloremque, praesentium autem placeat obcaecati voluptates, at adipisci laborum nulla temporibus assumenda laudantium sit labore? Architecto dicta repudiandae quisquam minus mollitia.</p>` +
    `<h2>Başlık H2</h2>` +
    `</br>` +
    `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae doloremque, praesentium autem placeat obcaecati voluptates, at adipisci laborum nulla temporibus assumenda laudantium sit labore? Architecto dicta repudiandae quisquam minus mollitia.</p>` +
    `<h3>Başlık H3</h3>` +
    `</br>` +
    `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae doloremque, praesentium autem placeat obcaecati voluptates, at adipisci laborum nulla temporibus assumenda laudantium sit labore? Architecto dicta repudiandae quisquam minus mollitia.</p>` +
    `<h3>Başlık H3</h3>` +
    `</br>` +
    `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae doloremque, praesentium autem placeat obcaecati voluptates, at adipisci laborum nulla temporibus assumenda laudantium sit labore? Architecto dicta repudiandae quisquam minus mollitia.</p>` +
    `<h4>Başlık H4</h4>` +
    `</br>` +
    `<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae doloremque, praesentium autem placeat obcaecati voluptates, at adipisci laborum nulla temporibus assumenda laudantium sit labore? Architecto dicta repudiandae quisquam minus mollitia.</p>`,
  code: "ABJ-100",
  brand: "Gammi",
  mainCategory: "Kadın",
  mainCategory_slug: "kadin",
  category: "İç Giyim",
  category_slug: "ic-giyim",
  subCategory: "Takım",
  subCategory_slug: "takim",
  images: [
    "/assets/products/product5.webp",
    "/assets/products/product2.webp",
    "/assets/products/product3.webp",
    "/assets/products/product4.webp",
    "/assets/products/product.webp",
  ],
  rating: 4.9,
  total_comment: 864,
  price: 460,
  discount: 10,
  stock: 50,
  tags: [
    "Amor Bralet Jartiyer",
    "Kırmızı İç Çamaşır Takımı",
    "Kırmızı Bralet Jartiyer",
  ],
  product_group: {
    group_name: "Renk",
    products: [
      {
        choise_name: "Kırmızı",
        product: {
          title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
          slug: "amor-bralet-jartiyer-ic-camasir-takimi",
          code: "ABJ-100",
          mainCategory_slug: "kadin",
          category_slug: "ic-giyim",
          images: [
            "/assets/products/product5.webp",
            "/assets/products/product2.webp",
            "/assets/products/product3.webp",
            "/assets/products/product4.webp",
            "/assets/products/product.webp",
          ],
        },
      },
      {
        choise_name: "Mavi",
        product: {
          title: "Blue Bralet Dress",
          slug: "blue-bralet-dress",
          code: "BBD-103",
          mainCategory_slug: "kadin",
          category_slug: "ic-giyim",
          images: [
            "/assets/products/product14.webp",
            "/assets/products/product15.webp",
            "/assets/products/product16.webp",
          ],
        },
      },
      {
        choise_name: "Bordo",
        product: {
          title: "Burgundy Bralet Dress",
          slug: "burgundy-bralet-dress",
          code: "BBD-102",
          mainCategory_slug: "kadin",
          category_slug: "ic-giyim",
          images: [
            "/assets/products/product11.webp",
            "/assets/products/product12.webp",
            "/assets/products/product16.webp",
            "/assets/products/product17.webp",
          ],
        },
      },
    ],
  },
  attributes: [
    {
      required: true,
      attr_title: "Beden",
      attr_options: [
        { option_name: "XS", option_stock: 50 },
        { option_name: "S", option_stock: 50 },
        { option_name: "M", option_stock: 50 },
        { option_name: "L", option_stock: 50 },
        { option_name: "XL", option_stock: 50 },
        { option_name: "XXL", option_stock: 0 },
        { option_name: "3XL", option_stock: 50 },
        { option_name: "4XL", option_stock: 50 },
        { option_name: "5XL", option_stock: 50 },
      ],
    },
    {
      required: true,
      attr_title: "Boy",
      attr_options: [
        { option_name: "150", option_stock: 50 },
        { option_name: "151", option_stock: 0 },
        { option_name: "152", option_stock: 50 },
        { option_name: "153", option_stock: 50 },
        { option_name: "154", option_stock: 50 },
        { option_name: "155", option_stock: 50 },
        { option_name: "156", option_stock: 50 },
        { option_name: "157", option_stock: 50 },
        { option_name: "158", option_stock: 50 },
        { option_name: "159", option_stock: 50 },
        { option_name: "160", option_stock: 50 },
        { option_name: "161", option_stock: 50 },
        { option_name: "162", option_stock: 50 },
        { option_name: "163", option_stock: 50 },
        { option_name: "164", option_stock: 50 },
        { option_name: "165", option_stock: 50 },
      ],
    },
  ],
  choise_required: true,
  status: true,
  featured_status: false,
  total_sold: 0,
  meta_title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
  meta_description:
    "Amor bralet jartiyer iç çamaşır takımı çok uygun fiyatlarla sadece web sitemizde.",
  created_at: new Date("2024-06-14T13:24:59.000000Z"),
  updated_at: null,
};

export const discountCodes = [
  {
    code: "CODE01",
    isPercentage: true,
    discount: 10,
  },
  {
    code: "CODE02",
    isPercentage: false,
    discount: 200,
  },
  {
    code: "CODE03",
    isPercentage: true,
    discount: 20,
  },
];
