export const generals = {
  site_name: "Batubutik",
  free_shipping: 1000,
  socials: [
    { platform: "Facebook", url: "/" },
    { platform: "Twitter", url: "/" },
    { platform: "İnstagram", url: "/" },
    { platform: "Youtube", url: "/" },
  ],
  address: "Meclis Mahallesi Derviş Sk. Fuat Ozal Apt No 38/1 Sancaktepe",
  email: "batubutik@info.com",
  phone: "08505058515",
  tags: [
    "Dantel İç Giyim",
    "Ekonomik İç Giyim",
    "Fantezi giyim",
    "Kadın iç giyim",
    "Kadın İç Çamaşır",
    "Likra İç Giyim",
    "Lüks İç Giyim",
    "Takım İç Giyim",
  ],
  return_conditions:
    'Beni en çok ne mutlu ediyor, biliyor musunuz? VALORANT topluluğunun ta kendisi. Ayrıca selam, Ben Jo-Ellen. Kasım 2023 Topluluk Özeti\'yle karşınızdayım. Her ay interneti gezip en havalı, en komik, en tatlı hayran çalışmalarınızı, cosplay\'lerinizi ve çok daha fazlasını görmek beni gerçekten mutlu ediyor. Aylardır bunu yapıyorum ve topluluk beni hâlâ mükemmel içeriklerle şaşırtmayı başarabiliyor.\n\n            Sıcak çikolatamızı yudumlayarak içimizi ısıtacağımız soğuk kış günlerine giderek yaklaşıyoruz. O yüzden 2023 kasımında üzerinde çalıştığınız içeriklerden bazılarını sizin için derledim.\n\n            KASIM AYININ HAYRAN ÇALIŞMALARI\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt02a182088c429fc9/656696f02d2f237766f3d691/11302023_CommunityRoundupNovember2023Article_XuanXuanOW.png">\n\n            @XuanXuanOW, Çin\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/bltec4a9e7f8dead1e6/656697521204cd6a9aca63da/11302023_CommunityRoundupNovember2023Article_Tokoyoneyami_77.gif">\n\n            @Tokoyoneyami_77, Japonya\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/bltc59db0f8ee5a4a93/656697ae36b5458213cd7b70/11302023_CommunityRoundupNovember2023Article_ECLIPIXM.jpg">\n\n            @ECLIPIXM, Avustralya\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt88b084f91395ef91/65669829ac4c41334994d499/11302023_CommunityRoundupNovember2023Article_dogbread_03.jpg">\n\n            @dogbread_03, Güney Kore\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt04ee977af62bd98c/656698897e63e324ab10ff26/11302023_CommunityRoundupNovember2023Article_kivizza_illust.jpg">\n\n            @kivizza_illust, Rusya\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blta89fe5663c26388a/656698da867c0bbe3738a1f8/11302023_CommunityRoundupNovember2023Article_charameldraws_RESIZED.jpg">\n\n            @charameldraws, Filipinler\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt08c189886355dbd2/6576d3600a4c053d864952d0/AskVal_BansByType_Graph_TR.jpg">\n\n            @qwq_qwp_pwp, Rusya',
};

export const navLinks = [
  {
    title: "Anasayfa",
    url: "/",
  },
  {
    title: "Mağaza",
    url: "/magaza",
  },
  {
    title: "Blog",
    url: "/blog",
  },
  {
    title: "Hakkımızda",
    url: "/hakkimizda",
  },
  {
    title: "İletişim",
    url: "/iletisim",
  },
];

export const categories = [
  {
    name: "Erkek",
    slug: "erkek",
    product_count: 0,
    sub_categories: [
      { name: "Üst Giyim", slug: "ust-giyim", product_count: 0 },
      { name: "Alt Giyim", slug: "alt-giyim", product_count: 0 },
    ],
  },
  {
    name: "Kadın",
    slug: "kadin",
    product_count: 6,
    sub_categories: [
      { name: "Üst Giyim", slug: "ust-giyim", product_count: 0 },
      { name: "Alt Giyim", slug: "alt-giyim", product_count: 0 },
      { name: "İç Giyim", slug: "ic-giyim", product_count: 6 },
    ],
  },
  {
    name: "Çocuk",
    slug: "cocuk",
    product_count: 0,
    sub_categories: [
      { name: "Üst Giyim", slug: "ust-giyim", product_count: 0 },
      { name: "Alt Giyim", slug: "alt-giyim", product_count: 0 },
    ],
  },
  {
    name: "Aksesuar",
    slug: "aksesuar",
    product_count: 0,
  },
];

export const instantProducts = [
  {
    id: 1,
    title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
    slug: "amor-bralet-jartiyer-ic-camasir-takimi",
    code: "ABJ-100",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product5.webp",
      "/assets/products/product2.webp",
      "/assets/products/product3.webp",
      "/assets/products/product4.webp",
      "/assets/products/product.webp",
    ],
    rating: 4.9,
    price: 460,
    discount: 10,
    stock: 50,
    choise_required: false,
    attributes: [
      {
        required: true,
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
          { option_name: "M", option_stock: 50 },
          { option_name: "L", option_stock: 50 },
          { option_name: "XL", option_stock: 50 },
          { option_name: "XXL", option_stock: 0 },
          { option_name: "3XL", option_stock: 50 },
          { option_name: "4XL", option_stock: 50 },
          { option_name: "5XL", option_stock: 50 },
        ],
      },
      {
        required: true,
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 2,
    title: "Black Bralet Dress",
    slug: "black-bralet-dress",
    code: "BBD-101",
    brand: "Batubutik",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product6.webp",
      "/assets/products/product7.webp",
      "/assets/products/product8.webp",
      "/assets/products/product9.webp",
    ],
    rating: 4.4,
    price: 320,
    discount: 30,
    stock: 50,
    choise_required: false,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
          { option_name: "M", option_stock: 50 },
        ],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 3,
    title: "Burgundy Bralet Dress",
    slug: "burgundy-bralet-dress",
    code: "BBD-102",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product10.webp",
      "/assets/products/product11.webp",
      "/assets/products/product12.webp",
      "/assets/products/product13.webp",
    ],
    rating: 4.1,
    price: 370,
    discount: 0,
    stock: 50,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
          { option_name: "M", option_stock: 50 },
        ],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 4,
    title: "Blue Bralet Dress",
    slug: "blue-bralet-dress",
    code: "BBD-103",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product14.webp",
      "/assets/products/product15.webp",
      "/assets/products/product16.webp",
    ],
    rating: 3.8,
    price: 410,
    discount: 15,
    stock: 50,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [
          { option_name: "XS", option_stock: 50 },
          { option_name: "S", option_stock: 50 },
        ],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 5,
    title: "Burgundy Bralet Dress 2",
    slug: "burgundy-bralet-dress-2",
    code: "BBD-104",
    brand: "Gammi",
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: [
      "/assets/products/product11.webp",
      "/assets/products/product12.webp",
      "/assets/products/product16.webp",
      "/assets/products/product17.webp",
    ],
    rating: 2.4,
    price: 410,
    discount: 0,
    stock: 0,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [{ option_name: "5XL", option_stock: 50 }],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-14T13:24:59.000000Z"),
    updated_at: null,
  },
  {
    id: 6,
    title: "Tek Fotoğraflı Ürün",
    slug: "tek-fotograf-urun",
    code: "TFU-100",
    brand: null,
    mainCategory: "Kadın",
    mainCategory_slug: "kadin",
    category: "İç Giyim",
    category_slug: "ic-giyim",
    images: ["/assets/products/product15.webp"],
    rating: 2.4,
    price: 410,
    discount: 0,
    stock: 10,
    choise_required: true,
    attributes: [
      {
        attr_title: "Beden",
        attr_options: [{ option_name: "5XL", option_stock: 50 }],
      },
      {
        attr_title: "Boy",
        attr_options: [
          { option_name: "150", option_stock: 50 },
          { option_name: "151", option_stock: 0 },
          { option_name: "152", option_stock: 50 },
          { option_name: "153", option_stock: 50 },
          { option_name: "154", option_stock: 50 },
          { option_name: "155", option_stock: 50 },
          { option_name: "156", option_stock: 50 },
          { option_name: "157", option_stock: 50 },
          { option_name: "158", option_stock: 50 },
          { option_name: "159", option_stock: 50 },
          { option_name: "160", option_stock: 50 },
          { option_name: "161", option_stock: 50 },
          { option_name: "162", option_stock: 50 },
          { option_name: "163", option_stock: 50 },
          { option_name: "164", option_stock: 50 },
          { option_name: "165", option_stock: 50 },
        ],
      },
    ],
    status: true,
    featured_status: false,
    total_sold: 0,
    created_at: new Date("2024-06-15T13:24:59.000000Z"),
    updated_at: null,
  },
];

export const instantProductDetail = {
  title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
  slug: "amor-bralet-jartiyer-ic-camasir-takimi",
  content:
    'Selamlar, ben Matt "K3o" Paoletti. Hilecileri karşılaşmalarınızdan nasıl uzak tuttuğumuza dair en güncel gelişmeleri paylaşmak için VALORANT Hile Koruması Ekibi adına karşınızdayım.\n\n            Ekibimiz her zamanki gibi hem rekabete dayalı sırada hem de espor sahnesinde rekabet bütünlüğünü sağlamaya kendini adamış durumda. Bu bağlılık hile yazılımlarıyla hile karşıtı yazılımlar arasındaki "yarışı" kazanmayı da kapsıyor, ki bu yazımızda bundan detaylıca bahsedeceğiz.\n\n            ÖZET:\n\n            Oyundan uzaklaştırma cezalarının sayısı çoğunlukla hile yapmaya engel olacak şekilde normal seviyelerde seyrediyor.\n            Hile geliştiricileri sosyal medyada reklam yaparak yeni müşteriler kazanmaya çalışıyorlar.\n            Ekibimiz geliştirilen yeni hile yöntemlerini radarında tutuyor ve Vanguard üzerinden bu hilelerin etkilerinin azaltılması için özel teknolojiler geliştiriyor.\n            Çeşitli risk unsurları taşıyan oyunculara ek koruma sağlayacak VAN:KISITLAMA adında yeni bir sistem çıkarıyoruz.\n            Oyundan Uzaklaştırmalar\n            Hilecilerin Vanguard\'ı giderek karmaşıklaşan şekillerde aşma girişimlerine rağmen oyundan uzaklaştırma cezalarının sayısı genel itibarıyla aynı seviyelerde seyrediyor. Aşağıdaki tabloda VALORANT\'tan ID uzaklaştırması alan oyuncuların donanımsal, manuel uzaklaştırma ve otomatik sistem tespitiyle uzaklaştırma şeklinde olmak üzere nasıl oyundan uzaklaştırıldıkları görülüyor.\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt08c189886355dbd2/6576d3600a4c053d864952d0/AskVal_BansByType_Graph_TR.jpg">\n\n            Aynı bilgisayarda birden fazla hesap aracılığıyla hile kullanarak sürekli ceza alan oyuncular hâlâ oyundan uzaklaştırma cezalarının ağırlıklı çoğunluğunu oluşturuyor. Bu hilecileri ekosistemimizden kalıcı olarak uzaklaştırmanın yollarını aramaya devam ediyoruz.\n\n            Sosyal Medya ve Hileler\n            Sosyal medyada hile olduğu bariz belli olan ancak "tespit edilemez" diye övülerek reklamı veya yayını yapılan VALORANT içerikleri görmüş olabilirsiniz. Vanguard varken bu kadar bariz hile kullanımının tespit edilememesi imkânsız olduğu için bu hilelerin görünürde herhangi bir sonucu bulunmadan nasıl yayınlandığını düşünüyor olabilirsiniz.\n\n            Aslında bu "canlı yayınların" ağırlıklı çoğunluğu önceden kaydedilmiş videolar. Hile geliştiricileri ürünlerinin reklamını yapmak için görüntülenme sayılarına güvenerek sosyal medyadaki insanları yanıltıyor. Bu hileciler hızlı bir şekilde oyundan uzaklaştırılsalar da birkaç videoluk içerik çıkarabiliyorlar ve bunları reklam olsun diye döngü şeklinde yayınlıyorlar. Bundan habersiz müşterileri ise videolara kanarak hileyi satın alıyor, kısa bir süreliğine oyunda keyifle kullanıyor ve ardından hızla oyundan uzaklaştırılıyorlar. Buna rağmen hile geliştiricileri satışlarını gerçekleştiriyor ve tabii oyundan uzaklaştırılan oyunculara para iadesi de yapılmıyor.\n\n            Hile Yazılımlarıyla Hile Karşıtı Yazılımlar Arasındaki Yarış\n            Vanguard\'ın güçlü engelleme katmanlarından ötürü hileciler sistemde bir açık bulmak için yeni modeller deniyorlar. VALORANT\'taki hileci topluluklarda gördüğümüz en gelişmiş yöntemlerden birisi hilecilerin donanım cihazları kullanarak Vanguard\'ı saf dışı bırakmaya çalıştığı Doğrudan Bellek Erişimi (DMA) hileleri.\n\n            Aşağıda bu girişimin nasıl bir şey olduğunu görebilirsiniz:\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8f1b1675cc527747/6576d3d019da2682471e884b/Val_Anti-Cheat_Update_DMa_Attack_Article_Graph_TR.jpg">\n\n            Bu cihazların VALORANT\'ta etkili şekilde kullanılabilmesini engellemek adına sınıfının en iyisi olduğunu düşündüğümüz bir teknoloji geliştirerek sistemimize entegre ettik.\n\n            Bu tür hile yöntemleri rekabet sahnesinin en yüksek seviyelerinde oynayan oyuncular tarafından da orantısız şekilde kullanılmaya çalışılıyor. Biz de yeni güvenlik önlemlerimizin güvenliğin en önemli olduğu alanda hayata geçirildiğinden emin olmak için ekstra birkaç adım atıyoruz.\n\n            Güvenlik Sağlama Protokolleri\n            Vanguard Anti-Cheat için VAN:KISITLAMA sistemi çıkıyor. Bu sistemde belirli risk unsurları taşıdığını belirlediğimiz oyunculardan ilave güvenlik gereksinimleri talep edeceğiz.\n\n            <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt06189b7b81be33ea/6576d3ecc5fb310abd9f90b6/Val_Vanguard_Restriction_System_TR.jpg">\n\n            Cihazlarda genel güvenlik özellikleri kullanarak hilecilerin koruma sistemlerimizi aşma yoluyla karşılaşmaları olumsuz etkileme girişimlerinin çoğuna engel olabiliyoruz. Çeşitli davranışsal tespit sistemlerimiz şüpheli davranışları belirlerken oyuncular da rekabet bütünlüğünün korunabilmesi adına yapmaları gereken cihaz değişikliklerinden haberdar edilecekler.\n\n            Amacımız yalnızca risk unsurlarından etkilenmiş oyuncuların standartlarımıza uyduklarından emin olmak olduğu için bu müdahaleler ceza olarak nitelendirilmiyor. Ayrıntılı bilgi için bu sayfayı ziyaret edebilirsiniz. Eğer herhangi bir sorunla karşılaşırsanız lütfen Oyuncu Destek Ekibi\'yle iletişime geçin.',
  code: "ABJ-100",
  brand: "Gammi",
  mainCategory: "Kadın",
  mainCategory_slug: "kadin",
  category: "İç Giyim",
  category_slug: "ic-giyim",
  subCategory: "Takım",
  subCategory_slug: "takim",
  images: [
    "/assets/products/product5.webp",
    "/assets/products/product2.webp",
    "/assets/products/product3.webp",
    "/assets/products/product4.webp",
    "/assets/products/product.webp",
  ],
  rating: 4.9,
  total_comment: 864,
  price: 460,
  discount: 10,
  stock: 50,
  tags: [
    "Amor Bralet Jartiyer",
    "Kırmızı İç Çamaşır Takımı",
    "Kırmızı Bralet Jartiyer",
  ],
  product_group: {
    group_name: "Renk",
    products: [
      { choise_name: "Kırmızı", code: "BBD-103" },
      { choise_name: "Bordo", code: "BBD-102" },
    ],
  },
  attributes: [
    {
      required: true,
      attr_title: "Beden",
      attr_options: [
        { option_name: "XS", option_stock: 50 },
        { option_name: "S", option_stock: 50 },
        { option_name: "M", option_stock: 50 },
        { option_name: "L", option_stock: 50 },
        { option_name: "XL", option_stock: 50 },
        { option_name: "XXL", option_stock: 0 },
        { option_name: "3XL", option_stock: 50 },
        { option_name: "4XL", option_stock: 50 },
        { option_name: "5XL", option_stock: 50 },
      ],
    },
    {
      required: true,
      attr_title: "Boy",
      attr_options: [
        { option_name: "150", option_stock: 50 },
        { option_name: "151", option_stock: 0 },
        { option_name: "152", option_stock: 50 },
        { option_name: "153", option_stock: 50 },
        { option_name: "154", option_stock: 50 },
        { option_name: "155", option_stock: 50 },
        { option_name: "156", option_stock: 50 },
        { option_name: "157", option_stock: 50 },
        { option_name: "158", option_stock: 50 },
        { option_name: "159", option_stock: 50 },
        { option_name: "160", option_stock: 50 },
        { option_name: "161", option_stock: 50 },
        { option_name: "162", option_stock: 50 },
        { option_name: "163", option_stock: 50 },
        { option_name: "164", option_stock: 50 },
        { option_name: "165", option_stock: 50 },
      ],
    },
  ],
  choise_required: true,
  status: true,
  featured_status: false,
  total_sold: 0,
  meta_title: "Amor Bralet Jartiyer İç Çamaşır Takımı",
  meta_description:
    "Amor bralet jartiyer iç çamaşır takımı çok uygun fiyatlarla sadece web sitemizde.",
  created_at: new Date("2024-06-14T13:24:59.000000Z"),
  updated_at: null,
};
